create table if not exists public.words (
  id bigint generated by default as identity primary key,
  word text not null unique,
  pronunciation text not null default '',
  part_of_speech text not null default 'other',
  meaning_ja text not null default '',
  example_en text not null default '',
  example_ja text not null default '',
  cloze_examples text not null default '[]',
  category text not null default 'Uncategorized',
  difficulty text not null default '3',
  low_frequency boolean not null default false,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  last_studied text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.words
add column if not exists part_of_speech text not null default 'other';

alter table public.words
add column if not exists low_frequency boolean not null default false;

alter table public.words
add column if not exists cloze_examples text not null default '[]';

notify pgrst, 'reload schema';

update public.words
set part_of_speech = case lower(word)
  when 'incorporate' then 'verb'
  when 'consolidate' then 'verb'
  when 'appropriate' then 'adjective'
  when 'implement' then 'verb'
  when 'overlook' then 'verb'
  when 'fatigue' then 'noun'
  when 'retention' then 'noun'
  when 'elaborate' then 'verb'
  when 'conversely' then 'adverb'
  when 'recurrent' then 'adjective'
  else part_of_speech
end
where part_of_speech = 'other';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists words_set_updated_at on public.words;

create trigger words_set_updated_at
before update on public.words
for each row
execute function public.set_updated_at();

alter table public.words enable row level security;

create index if not exists words_wrong_count_idx on public.words (wrong_count desc);
create index if not exists words_last_studied_idx on public.words (last_studied);

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.words to service_role;
grant usage, select on sequence public.words_id_seq to service_role;

create table if not exists public.app_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

drop trigger if exists app_settings_set_updated_at on public.app_settings;

create trigger app_settings_set_updated_at
before update on public.app_settings
for each row
execute function public.set_updated_at();

alter table public.app_settings enable row level security;

grant select, insert, update, delete on table public.app_settings to service_role;
